### ISSUE TITLE
import infoblox_client.objects : SyntaxError

### ISSUE THREAD

**Issue by seisen** [infobloxopen/infoblox-client#113]
test code 
`from infoblox_client import objects`

python 2.7.5 : OK

python 2.6.6 : KO
```
Traceback (most recent call last):
  File "e2.py", line 1, in <module>
    from infoblox_client import objects
  File "/usr/local/lib/python2.6/dist-packages/infoblox_client/objects.py", line 77
    for field in self._fields + self._shadow_fields
      ^
SyntaxError: invalid syntax


```

**Comment by bondar-pavel** [comment]
@seisen I tried to add support of python 2.6, but it's hardly possible.
Fixing syntax error for 'for field in self._fields + self._shadow_fields' is easy, but the bigger issue is that  modules oslo_config and oslo_log are not py26 compatible. And infoblox-client depend on them.
So with python 2.6 import will fail even after py26 syntax error is fixed.

```
======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'total_ordering')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/apostal/PycharmProjects/infoblox-client/.tox/py26/lib/python2.6/site-packages/nose/loader.py", line 418, i
n loadTestsFromName
    addr.filename, addr.module)
  File "/home/apostal/PycharmProjects/infoblox-client/.tox/py26/lib/python2.6/site-packages/nose/importer.py", line 47,
in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/apostal/PycharmProjects/infoblox-client/.tox/py26/lib/python2.6/site-packages/nose/importer.py", line 94,
in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/apostal/PycharmProjects/infoblox-client/tests/test_connector.py", line 23, in <module>
    from infoblox_client import connector
  File "/home/apostal/PycharmProjects/infoblox-client/infoblox_client/connector.py", line 34, in <module>
    from infoblox_client import utils
  File "/home/apostal/PycharmProjects/infoblox-client/infoblox_client/utils.py", line 20, in <module>
    from oslo_log import log as logging
  File "/home/apostal/PycharmProjects/infoblox-client/.tox/py26/lib/python2.6/site-packages/oslo_log/log.py", line 42, i
n <module>
    from oslo_config import cfg
  File "/home/apostal/PycharmProjects/infoblox-client/.tox/py26/lib/python2.6/site-packages/oslo_config/cfg.py", line 63
6, in <module>
    @functools.total_ordering
AttributeError: 'module' object has no attribute 'total_ordering'
```

So python 2.6 is not supported for infoblox-client.
