### ISSUE TITLE
ib_objects.FixedAddress.search fails

### ISSUE THREAD

**Issue by hosunghwang** [infobloxopen/infoblox-client#17]
While xecuting the following code from deallocate(), I got errors below. 

fa = ib_objects.FixedAddress.search(self._ib_context.connector,
                                    network_view=mapped_netview,
                                    ip=ip_address)

2015-11-24 10:36:25.421 ERROR neutron.api.v2.resource [req-52422d03-c7f5-48d7-9c8f-91be7be0df17 admin 4befcd541d594ac6a60389243a0b0ef6] delete failed
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource Traceback (most recent call last):
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/api/v2/resource.py", line 83, in resource
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_db/api.py", line 136, in wrapper
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     return f(*args, **kwargs)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 119, in __exit__
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_db/api.py", line 136, in wrapper
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     return f(*args, **kwargs)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/api/v2/base.py", line 521, in delete
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     obj_deleter(request.context, id, **kwargs)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/plugins/ml2/plugin.py", line 808, in delete_network
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     self._delete_ports(context, port_ids)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/plugins/ml2/plugin.py", line 714, in _delete_ports
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     self.delete_port(context, port_id)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 119, in __exit__
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/plugins/ml2/plugin.py", line 714, in _delete_ports
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     self.delete_port(context, port_id)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/plugins/ml2/plugin.py", line 1367, in delete_port
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     super(Ml2Plugin, self).delete_port(context, id)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/db/db_base_plugin_v2.py", line 1237, in delete_port
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     self.ipam.delete_port(context, id)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/db/ipam_pluggable_backend.py", line 351, in delete_port
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     port['fixed_ips'])
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/db/ipam_pluggable_backend.py", line 57, in _ipam_deallocate_ips
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     ipam_subnet.deallocate(ip['ip_address'])
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 119, in __exit__
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/opt/stack/neutron/neutron/db/ipam_pluggable_backend.py", line 57, in _ipam_deallocate_ips
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     ipam_subnet.deallocate(ip['ip_address'])
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/networking_infoblox/ipam/driver.py", line 320, in deallocate
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     ip=ip_address)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/infoblox_client/objects.py", line 250, in search
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     connector, **kwargs)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/infoblox_client/objects.py", line 231, in _search
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     ib_obj_for_search = cls(connector, **kwargs)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/infoblox_client/objects.py", line 135, in __new__
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     cls).__new__(cls.get_class_from_args(kwargs))
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/bdb.py", line 53, in trace_dispatch
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     return self.dispatch_return(frame, arg)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/bdb.py", line 88, in dispatch_return
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     self.user_return(frame, arg)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/pdb.py", line 190, in user_return
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     self.interaction(frame, None)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/pdb.py", line 209, in interaction
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     self.print_stack_entry(self.stack[self.curindex])
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/pdb.py", line 900, in print_stack_entry
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     prompt_prefix)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/bdb.py", line 381, in format_stack_entry
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     s = s + repr.repr(rv)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/repr.py", line 24, in repr
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     return self.repr1(x, self.maxlevel)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/repr.py", line 34, in repr1
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     s = __builtin__.repr(x)
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/infoblox_client/objects.py", line 69, in __repr__
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     for field in self._fields + self._shadow_fields
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/infoblox_client/objects.py", line 70, in <dictcomp>
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     if getattr(self, field) is not None}
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource   File "/usr/local/lib/python2.7/dist-packages/infoblox_client/objects.py", line 59, in __getattr__
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource     raise AttributeError
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource AttributeError
2015-11-24 10:36:25.421 TRACE neutron.api.v2.resource

**Comment by bondar-pavel** [comment]
Is it fails only in pdb?
From trace I see it fails on __repr__ routine which is executed only in debugger.

**Comment by bondar-pavel** [comment]
From stack trace analysis it looks like debugger tries to show object representation before __init__ is finished.
__repr__ tries to get values of (self._fields + self._shadow_fields) and fails because some of them does not exist yet.
Once __init__ is finished fields (self._fields + self._shadow_fields) are already exists in object.

**Comment by bondar-pavel** [comment]
And Fixed IP creation/search works as expected in my test env:
```
In [8]: fa = objects.FixedAddress.create(conn, network_view='default', ip='192.168.95.25', mac='00:00:00:11:00:00')
/home/pavel/.venv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/home/pavel/.venv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

In [9]: fa
Out[9]: FixedAddressV4: network_view="default", ip="192.168.95.25", ipv4addr="192.168.95.25", mac="00:00:00:11:00:00", extattrs="{}", _ref="fixedaddress/ZG5zLmZpeGVkX2FkZHJlc3MkMTkyLjE2OC45NS4yNS4wLi4:192.168.95.25/default"

In [10]:

In [10]: fa = objects.FixedAddress.search(conn, network_view='default', ip='192.168.95.25')
/home/pavel/.venv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

In [11]: fa
Out[11]: FixedAddressV4: network_view="default", ip="192.168.95.25", ipv4addr="192.168.95.25", mac="00:00:00:11:00:00", extattrs="{}", _ref="fixedaddress/ZG5zLmZpeGVkX2FkZHJlc3MkMTkyLjE2OC45NS4yNS4wLi4:192.168.95.25/default"

In [12]: fa = objects.FixedAddress.search(conn, network_view='default', ip='192.168.95.26')
/home/pavel/.venv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

In [13]: fa
