### ISSUE TITLE
Remove extattrs from object

### ISSUE THREAD

**Issue by jonnic** [infobloxopen/infoblox-client#244]
Is there a mechanism for removing extensible attributes from an object? In my case I'm using a VLAN name associated with a network object.
I've tried creating a new EA object without the entries I want and assigning it to the network:-

```n=objects.Network.search(conn, network='192.168.66.0/24')
d=n.extattr.to_dict()
## <delete the keys from the dictionary>
n.extattr.from_dict(d)
n.update()
```
Results in the error:-
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.6/site-packages/infoblox_client/objects.py", line 402, in update
    update_fields = self.to_dict(search_fields='exclude')
  File "venv/lib/python3.6/site-packages/infoblox_client/objects.py", line 283, in to_dict
    return {field: self.field_to_dict(field) for field in fields
  File "venv/lib/python3.6/site-packages/infoblox_client/objects.py", line 284, in <dictcomp>
    if getattr(self, field, None) is not None}
  File "venv/lib/python3.6/site-packages/infoblox_client/objects.py", line 267, in field_to_dict
    return self.value_to_dict(value)
  File "venv/lib/python3.6/site-packages/infoblox_client/objects.py", line 260, in value_to_dict
    return value.to_dict() if hasattr(value, 'to_dict') else value
TypeError: to_dict() missing 1 required positional argument: 'self'
```
when the network update is called.

Am I doing something wrong?

**Comment by saiprasannasastry** [comment]
can you paste the complete code here.

**Comment by AvRajath** [comment]
Closing this issue as we heard no response.
