### ISSUE TITLE
MAC required to create IPv6 address

### ISSUE THREAD

**Issue by tucked** [infobloxopen/infoblox-client#346]
```
>>> from infoblox_client import objects
>>> objects.IP.create("127.0.0.1")
IPv4: ipv4addr="127.0.0.1", ip="127.0.0.1"
>>> objects.IP.create("::1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.8/site-packages/infoblox_client/objects.py", line 543, in create
    return IPv6(ip=ip, duid=ib_utils.generate_duid(mac),
  File "venv/lib/python3.8/site-packages/infoblox_client/utils.py", line 47, in generate_duid
    raise ValueError("Invalid argument was passed")
ValueError: Invalid argument was passed
```
Workaround:
```
>>> ip = objects.IPv6()
>>> ip.ip = "::1"
>>> ip
IPv6: ipv6addr="::1", ip="::1"
```

**Comment by sarya-infoblox** [comment]
Hi @tucked 

We are working on a priority ticket as of now and will look into this issue as soon as I get some time.

**Comment by maxadamo** [comment]
@sarya-infoblox do you have an update on this issue?
